# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

lang1 = Language.create(name: "Python", description: "Python is an interpreted, high-level and general-purpose programming language.", img_url: "https://i.pinimg.com/564x/77/88/25/778825be381be66db27d56ba533034ea.jpg")
lang2 = Language.create(name: "JavaScript", description: "JavaScript is an object-oriented computer programming language commonly used to create interactive effects within web browsers.", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/480px-JavaScript-logo.png")
lang3 = Language.create(name: "Java", description: "Java is a class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.", img_url: "https://upload.wikimedia.org/wikipedia/en/3/30/Java_programming_language_logo.svg")
lang4 = Language.create(name: "C", description: "C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, with a static type system.", img_url: "https://ludu-assets.s3.amazonaws.com/course-icons/26/urA5bRhIewsQ2LgxuCu2")
lang5 = Language.create(name: "C#", description: "C# is a general-purpose, multi-paradigm programming language encompassing strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented, and component-oriented programming disciplines.", img_url: "https://seeklogo.com/images/C/c-sharp-c-logo-02F17714BA-seeklogo.com.png")
lang6 = Language.create(name: "C++", description: "C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language, or 'C with Classes'.", img_url: "https://sdtimes.com/wp-content/uploads/2018/03/cpppp.png")
lang7 = Language.create(name: "Go", description: "Go is a statically typed, compiled programming language.", img_url: "https://assets.deepsource.io/7effb93/images/blog/release-go-beta/go-logo.png")
lang8 = Language.create(name: "PHP", description: "PHP is a general-purpose scripting language especially suited to web development.", img_url: "https://cdn.worldvectorlogo.com/logos/php.svg")
lang9 = Language.create(name: "Swift", description: "Swift is a general-purpose, multi-paradigm, compiled programming language developed by Apple Inc. and the open-source community, first released in 2014.", img_url: "https://developer.apple.com/swift/images/swift-og.png")
lang10 = Language.create(name: "Ruby", description: "Ruby is an interpreted, high-level, general-purpose programming language.", img_url: "https://pngimg.com/uploads/ruby/ruby_PNG28.png")
lang11 = Language.create(name: "R", description: "R is a programming language and free software environment for statistical computing and graphics.", img_url: "https://www.r-project.org/logo/Rlogo.svg")
lang12 = Language.create(name: "TypeScript", description: "TypeScript is a programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript and adds optional static typing to the language. TypeScript is designed for development of large applications and transcompiles to JavaScript.", img_url: "https://miro.medium.com/max/816/1*mn6bOs7s6Qbao15PMNRyOA.png")
lang13 = Language.create(name: "Rust", description: "Rust is a multi-paradigm programming language focused on performance and safety, especially safe concurrency.", img_url: "https://www.vippng.com/png/detail/33-331403_rust-programming-language-black-logo-rust-programming-logo.png")
lang14 = Language.create(name: "Scala", description: "Scala is a general-purpose programming language providing support for both object-oriented programming and functional programming.", img_url: "https://www.scala-lang.org/resources/img/frontpage/scala-spiral.png")
lang15 = Language.create(name: "MATLAB", description: "MATLAB is a proprietary multi-paradigm programming language and numerical computing environment developed by MathWorks. MATLAB allows matrix manipulations, plotting of functions and data, implementation of algorithms, creation of user interfaces, and interfacing with programs written in other languages.", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Matlab_Logo.png/667px-Matlab_Logo.png")

topic1 = Topic.create(title: "Artificial Intelligence")
topic2 = Topic.create(title: "For Loops")
topic3 = Topic.create(title: "While Loops")
topic4 = Topic.create(title: "Variables & Data Types")
topic5 = Topic.create(title: "Math Operators")
topic6 = Topic.create(title: "Recursion")
topic7 = Topic.create(title: "Objects and Classes")
topic8 = Topic.create(title: "MVC")
topic9 = Topic.create(title: "Domain Modeling")
topic10 = Topic.create(title: "CyberSecurity")
topic11 = Topic.create(title: "Conditionals")
topic12 = Topic.create(title: "Enumerables")
topic13 = Topic.create(title: "Inheritance")
topic14 = Topic.create(title: "Algorithms")
topic15 = Topic.create(title: "Web Applications")
topic16 = Topic.create(title: "Arrays")
topic17 = Topic.create(title: "Data Analysis")
topic18 = Topic.create(title: "File Handling")
topic19 = Topic.create(title: "Source Control")
topic20 = Topic.create(title: "Events")
topic21 = Topic.create(title: "Polymorphism")

topic22 = Topic.create(title: "Factors")
topic23 = Topic.create(title: "Vectors")
topic24 = Topic.create(title: "Matrices")
topic25 = Topic.create(title: "Data Frames")
topic26 = Topic.create(title: "Charts & Graphs")


LangTopic.create(language_id: lang1.id, topic_id: topic1.id)
LangTopic.create(language_id: lang1.id, topic_id: topic2.id)
LangTopic.create(language_id: lang1.id, topic_id: topic3.id)
LangTopic.create(language_id: lang1.id, topic_id: topic4.id)
LangTopic.create(language_id: lang1.id, topic_id: topic5.id)
LangTopic.create(language_id: lang1.id, topic_id: topic6.id)
LangTopic.create(language_id: lang1.id, topic_id: topic7.id)
LangTopic.create(language_id: lang1.id, topic_id: topic8.id)
LangTopic.create(language_id: lang1.id, topic_id: topic9.id)
LangTopic.create(language_id: lang1.id, topic_id: topic10.id)
LangTopic.create(language_id: lang1.id, topic_id: topic11.id)
LangTopic.create(language_id: lang1.id, topic_id: topic12.id)
LangTopic.create(language_id: lang1.id, topic_id: topic13.id)
LangTopic.create(language_id: lang1.id, topic_id: topic14.id)
LangTopic.create(language_id: lang1.id, topic_id: topic15.id)
LangTopic.create(language_id: lang1.id, topic_id: topic16.id)
LangTopic.create(language_id: lang1.id, topic_id: topic17.id)
LangTopic.create(language_id: lang1.id, topic_id: topic18.id)
LangTopic.create(language_id: lang1.id, topic_id: topic19.id)

LangTopic.create(language_id: lang2.id, topic_id: topic1.id)
LangTopic.create(language_id: lang2.id, topic_id: topic2.id)
LangTopic.create(language_id: lang2.id, topic_id: topic3.id)
LangTopic.create(language_id: lang2.id, topic_id: topic4.id)
LangTopic.create(language_id: lang2.id, topic_id: topic5.id)
LangTopic.create(language_id: lang2.id, topic_id: topic6.id)
LangTopic.create(language_id: lang2.id, topic_id: topic7.id)
LangTopic.create(language_id: lang2.id, topic_id: topic8.id)
LangTopic.create(language_id: lang2.id, topic_id: topic9.id)
LangTopic.create(language_id: lang2.id, topic_id: topic10.id)
LangTopic.create(language_id: lang2.id, topic_id: topic11.id)
LangTopic.create(language_id: lang2.id, topic_id: topic12.id)
LangTopic.create(language_id: lang2.id, topic_id: topic13.id)
LangTopic.create(language_id: lang2.id, topic_id: topic14.id)
LangTopic.create(language_id: lang2.id, topic_id: topic15.id)
LangTopic.create(language_id: lang2.id, topic_id: topic16.id)
LangTopic.create(language_id: lang2.id, topic_id: topic17.id)
LangTopic.create(language_id: lang2.id, topic_id: topic18.id)
LangTopic.create(language_id: lang2.id, topic_id: topic19.id)
LangTopic.create(language_id: lang2.id, topic_id: topic20.id)

LangTopic.create(language_id: lang3.id, topic_id: topic1.id)
LangTopic.create(language_id: lang3.id, topic_id: topic2.id)
LangTopic.create(language_id: lang3.id, topic_id: topic3.id)
LangTopic.create(language_id: lang3.id, topic_id: topic4.id)
LangTopic.create(language_id: lang3.id, topic_id: topic5.id)
LangTopic.create(language_id: lang3.id, topic_id: topic6.id)
LangTopic.create(language_id: lang3.id, topic_id: topic7.id)
LangTopic.create(language_id: lang3.id, topic_id: topic8.id)
LangTopic.create(language_id: lang3.id, topic_id: topic9.id)
LangTopic.create(language_id: lang3.id, topic_id: topic10.id)
LangTopic.create(language_id: lang3.id, topic_id: topic11.id)
LangTopic.create(language_id: lang3.id, topic_id: topic12.id)
LangTopic.create(language_id: lang3.id, topic_id: topic13.id)
LangTopic.create(language_id: lang3.id, topic_id: topic14.id)
LangTopic.create(language_id: lang3.id, topic_id: topic15.id)
LangTopic.create(language_id: lang3.id, topic_id: topic16.id)
LangTopic.create(language_id: lang3.id, topic_id: topic17.id)
LangTopic.create(language_id: lang3.id, topic_id: topic18.id)
LangTopic.create(language_id: lang3.id, topic_id: topic19.id)
LangTopic.create(language_id: lang3.id, topic_id: topic20.id)
LangTopic.create(language_id: lang3.id, topic_id: topic21.id)

LangTopic.create(language_id: lang4.id, topic_id: topic1.id)
LangTopic.create(language_id: lang4.id, topic_id: topic2.id)
LangTopic.create(language_id: lang4.id, topic_id: topic3.id)
LangTopic.create(language_id: lang4.id, topic_id: topic4.id)
LangTopic.create(language_id: lang4.id, topic_id: topic5.id)
LangTopic.create(language_id: lang4.id, topic_id: topic6.id)
LangTopic.create(language_id: lang4.id, topic_id: topic7.id)
LangTopic.create(language_id: lang4.id, topic_id: topic8.id)
LangTopic.create(language_id: lang4.id, topic_id: topic9.id)
LangTopic.create(language_id: lang4.id, topic_id: topic10.id)
LangTopic.create(language_id: lang4.id, topic_id: topic11.id)
LangTopic.create(language_id: lang4.id, topic_id: topic12.id)
LangTopic.create(language_id: lang4.id, topic_id: topic13.id)
LangTopic.create(language_id: lang4.id, topic_id: topic14.id)
LangTopic.create(language_id: lang4.id, topic_id: topic15.id)
LangTopic.create(language_id: lang4.id, topic_id: topic16.id)
LangTopic.create(language_id: lang4.id, topic_id: topic17.id)
LangTopic.create(language_id: lang4.id, topic_id: topic18.id)
LangTopic.create(language_id: lang4.id, topic_id: topic19.id)
LangTopic.create(language_id: lang4.id, topic_id: topic20.id)

LangTopic.create(language_id: lang5.id, topic_id: topic1.id)
LangTopic.create(language_id: lang5.id, topic_id: topic2.id)
LangTopic.create(language_id: lang5.id, topic_id: topic3.id)
LangTopic.create(language_id: lang5.id, topic_id: topic4.id)
LangTopic.create(language_id: lang5.id, topic_id: topic5.id)
LangTopic.create(language_id: lang5.id, topic_id: topic6.id)
LangTopic.create(language_id: lang5.id, topic_id: topic7.id)
LangTopic.create(language_id: lang5.id, topic_id: topic8.id)
LangTopic.create(language_id: lang5.id, topic_id: topic9.id)
LangTopic.create(language_id: lang5.id, topic_id: topic10.id)
LangTopic.create(language_id: lang5.id, topic_id: topic11.id)
LangTopic.create(language_id: lang5.id, topic_id: topic12.id)
LangTopic.create(language_id: lang5.id, topic_id: topic13.id)
LangTopic.create(language_id: lang5.id, topic_id: topic14.id)
LangTopic.create(language_id: lang5.id, topic_id: topic15.id)
LangTopic.create(language_id: lang5.id, topic_id: topic16.id)
LangTopic.create(language_id: lang5.id, topic_id: topic17.id)
LangTopic.create(language_id: lang5.id, topic_id: topic18.id)
LangTopic.create(language_id: lang5.id, topic_id: topic19.id)
LangTopic.create(language_id: lang5.id, topic_id: topic20.id)
LangTopic.create(language_id: lang5.id, topic_id: topic21.id)

LangTopic.create(language_id: lang6.id, topic_id: topic1.id)
LangTopic.create(language_id: lang6.id, topic_id: topic2.id)
LangTopic.create(language_id: lang6.id, topic_id: topic3.id)
LangTopic.create(language_id: lang6.id, topic_id: topic4.id)
LangTopic.create(language_id: lang6.id, topic_id: topic5.id)
LangTopic.create(language_id: lang6.id, topic_id: topic6.id)
LangTopic.create(language_id: lang6.id, topic_id: topic7.id)
LangTopic.create(language_id: lang6.id, topic_id: topic8.id)
LangTopic.create(language_id: lang6.id, topic_id: topic9.id)
LangTopic.create(language_id: lang6.id, topic_id: topic10.id)
LangTopic.create(language_id: lang6.id, topic_id: topic11.id)
LangTopic.create(language_id: lang6.id, topic_id: topic12.id)
LangTopic.create(language_id: lang6.id, topic_id: topic13.id)
LangTopic.create(language_id: lang6.id, topic_id: topic14.id)
LangTopic.create(language_id: lang6.id, topic_id: topic15.id)
LangTopic.create(language_id: lang6.id, topic_id: topic16.id)
LangTopic.create(language_id: lang6.id, topic_id: topic17.id)
LangTopic.create(language_id: lang6.id, topic_id: topic18.id)
LangTopic.create(language_id: lang6.id, topic_id: topic19.id)
LangTopic.create(language_id: lang6.id, topic_id: topic20.id)
LangTopic.create(language_id: lang6.id, topic_id: topic21.id)

LangTopic.create(language_id: lang7.id, topic_id: topic1.id)
LangTopic.create(language_id: lang7.id, topic_id: topic2.id)
LangTopic.create(language_id: lang7.id, topic_id: topic3.id)
LangTopic.create(language_id: lang7.id, topic_id: topic4.id)
LangTopic.create(language_id: lang7.id, topic_id: topic5.id)
LangTopic.create(language_id: lang7.id, topic_id: topic6.id)
LangTopic.create(language_id: lang7.id, topic_id: topic7.id)
LangTopic.create(language_id: lang7.id, topic_id: topic8.id)
LangTopic.create(language_id: lang7.id, topic_id: topic9.id)
LangTopic.create(language_id: lang7.id, topic_id: topic10.id)
LangTopic.create(language_id: lang7.id, topic_id: topic11.id)
LangTopic.create(language_id: lang7.id, topic_id: topic12.id)
LangTopic.create(language_id: lang7.id, topic_id: topic13.id)
LangTopic.create(language_id: lang7.id, topic_id: topic14.id)
LangTopic.create(language_id: lang7.id, topic_id: topic15.id)
LangTopic.create(language_id: lang7.id, topic_id: topic16.id)
LangTopic.create(language_id: lang7.id, topic_id: topic17.id)
LangTopic.create(language_id: lang7.id, topic_id: topic18.id)
LangTopic.create(language_id: lang7.id, topic_id: topic19.id)

LangTopic.create(language_id: lang8.id, topic_id: topic1.id)
LangTopic.create(language_id: lang8.id, topic_id: topic2.id)
LangTopic.create(language_id: lang8.id, topic_id: topic3.id)
LangTopic.create(language_id: lang8.id, topic_id: topic4.id)
LangTopic.create(language_id: lang8.id, topic_id: topic5.id)
LangTopic.create(language_id: lang8.id, topic_id: topic6.id)
LangTopic.create(language_id: lang8.id, topic_id: topic7.id)
LangTopic.create(language_id: lang8.id, topic_id: topic8.id)
LangTopic.create(language_id: lang8.id, topic_id: topic9.id)
LangTopic.create(language_id: lang8.id, topic_id: topic10.id)
LangTopic.create(language_id: lang8.id, topic_id: topic11.id)
LangTopic.create(language_id: lang8.id, topic_id: topic12.id)
LangTopic.create(language_id: lang8.id, topic_id: topic13.id)
LangTopic.create(language_id: lang8.id, topic_id: topic14.id)
LangTopic.create(language_id: lang8.id, topic_id: topic15.id)
LangTopic.create(language_id: lang8.id, topic_id: topic16.id)
LangTopic.create(language_id: lang8.id, topic_id: topic17.id)
LangTopic.create(language_id: lang8.id, topic_id: topic18.id)
LangTopic.create(language_id: lang8.id, topic_id: topic19.id)

LangTopic.create(language_id: lang9.id, topic_id: topic1.id)
LangTopic.create(language_id: lang9.id, topic_id: topic2.id)
LangTopic.create(language_id: lang9.id, topic_id: topic3.id)
LangTopic.create(language_id: lang9.id, topic_id: topic4.id)
LangTopic.create(language_id: lang9.id, topic_id: topic5.id)
LangTopic.create(language_id: lang9.id, topic_id: topic6.id)
LangTopic.create(language_id: lang9.id, topic_id: topic7.id)
LangTopic.create(language_id: lang9.id, topic_id: topic8.id)
LangTopic.create(language_id: lang9.id, topic_id: topic9.id)
LangTopic.create(language_id: lang9.id, topic_id: topic10.id)
LangTopic.create(language_id: lang9.id, topic_id: topic11.id)
LangTopic.create(language_id: lang9.id, topic_id: topic12.id)
LangTopic.create(language_id: lang9.id, topic_id: topic13.id)
LangTopic.create(language_id: lang9.id, topic_id: topic14.id)
LangTopic.create(language_id: lang9.id, topic_id: topic15.id)
LangTopic.create(language_id: lang9.id, topic_id: topic16.id)
LangTopic.create(language_id: lang9.id, topic_id: topic17.id)
LangTopic.create(language_id: lang9.id, topic_id: topic18.id)
LangTopic.create(language_id: lang9.id, topic_id: topic19.id)

LangTopic.create(language_id: lang10.id, topic_id: topic1.id)
LangTopic.create(language_id: lang10.id, topic_id: topic2.id)
LangTopic.create(language_id: lang10.id, topic_id: topic3.id)
LangTopic.create(language_id: lang10.id, topic_id: topic4.id)
LangTopic.create(language_id: lang10.id, topic_id: topic5.id)
LangTopic.create(language_id: lang10.id, topic_id: topic6.id)
LangTopic.create(language_id: lang10.id, topic_id: topic7.id)
LangTopic.create(language_id: lang10.id, topic_id: topic8.id)
LangTopic.create(language_id: lang10.id, topic_id: topic9.id)
LangTopic.create(language_id: lang10.id, topic_id: topic10.id)
LangTopic.create(language_id: lang10.id, topic_id: topic11.id)
LangTopic.create(language_id: lang10.id, topic_id: topic12.id)
LangTopic.create(language_id: lang10.id, topic_id: topic13.id)
LangTopic.create(language_id: lang10.id, topic_id: topic14.id)
LangTopic.create(language_id: lang10.id, topic_id: topic15.id)
LangTopic.create(language_id: lang10.id, topic_id: topic16.id)
LangTopic.create(language_id: lang10.id, topic_id: topic17.id)
LangTopic.create(language_id: lang10.id, topic_id: topic18.id)
LangTopic.create(language_id: lang10.id, topic_id: topic19.id)


LangTopic.create(language_id: lang11.id, topic_id: topic2.id)
LangTopic.create(language_id: lang11.id, topic_id: topic3.id)
LangTopic.create(language_id: lang11.id, topic_id: topic4.id)
LangTopic.create(language_id: lang11.id, topic_id: topic5.id)
LangTopic.create(language_id: lang11.id, topic_id: topic6.id)
LangTopic.create(language_id: lang11.id, topic_id: topic11.id)
LangTopic.create(language_id: lang11.id, topic_id: topic16.id)
LangTopic.create(language_id: lang11.id, topic_id: topic17.id)
LangTopic.create(language_id: lang11.id, topic_id: topic18.id)
LangTopic.create(language_id: lang11.id, topic_id: topic22.id)
LangTopic.create(language_id: lang11.id, topic_id: topic23.id)
LangTopic.create(language_id: lang11.id, topic_id: topic24.id)
LangTopic.create(language_id: lang11.id, topic_id: topic25.id)
LangTopic.create(language_id: lang11.id, topic_id: topic26.id)

LangTopic.create(language_id: lang12.id, topic_id: topic1.id)
LangTopic.create(language_id: lang12.id, topic_id: topic2.id)
LangTopic.create(language_id: lang12.id, topic_id: topic3.id)
LangTopic.create(language_id: lang12.id, topic_id: topic4.id)
LangTopic.create(language_id: lang12.id, topic_id: topic5.id)
LangTopic.create(language_id: lang12.id, topic_id: topic6.id)
LangTopic.create(language_id: lang12.id, topic_id: topic7.id)
LangTopic.create(language_id: lang12.id, topic_id: topic8.id)
LangTopic.create(language_id: lang12.id, topic_id: topic9.id)
LangTopic.create(language_id: lang12.id, topic_id: topic10.id)
LangTopic.create(language_id: lang12.id, topic_id: topic11.id)
LangTopic.create(language_id: lang12.id, topic_id: topic12.id)
LangTopic.create(language_id: lang12.id, topic_id: topic13.id)
LangTopic.create(language_id: lang12.id, topic_id: topic14.id)
LangTopic.create(language_id: lang12.id, topic_id: topic15.id)
LangTopic.create(language_id: lang12.id, topic_id: topic16.id)
LangTopic.create(language_id: lang12.id, topic_id: topic17.id)
LangTopic.create(language_id: lang12.id, topic_id: topic18.id)
LangTopic.create(language_id: lang12.id, topic_id: topic19.id)
LangTopic.create(language_id: lang12.id, topic_id: topic20.id)

LangTopic.create(language_id: lang13.id, topic_id: topic1.id)
LangTopic.create(language_id: lang13.id, topic_id: topic2.id)
LangTopic.create(language_id: lang13.id, topic_id: topic3.id)
LangTopic.create(language_id: lang13.id, topic_id: topic4.id)
LangTopic.create(language_id: lang13.id, topic_id: topic5.id)
LangTopic.create(language_id: lang13.id, topic_id: topic6.id)
LangTopic.create(language_id: lang13.id, topic_id: topic7.id)
LangTopic.create(language_id: lang13.id, topic_id: topic8.id)
LangTopic.create(language_id: lang13.id, topic_id: topic9.id)
LangTopic.create(language_id: lang13.id, topic_id: topic10.id)
LangTopic.create(language_id: lang13.id, topic_id: topic11.id)
LangTopic.create(language_id: lang13.id, topic_id: topic12.id)
LangTopic.create(language_id: lang13.id, topic_id: topic13.id)
LangTopic.create(language_id: lang13.id, topic_id: topic14.id)
LangTopic.create(language_id: lang13.id, topic_id: topic15.id)
LangTopic.create(language_id: lang13.id, topic_id: topic16.id)
LangTopic.create(language_id: lang13.id, topic_id: topic17.id)
LangTopic.create(language_id: lang13.id, topic_id: topic18.id)
LangTopic.create(language_id: lang13.id, topic_id: topic20.id)

LangTopic.create(language_id: lang14.id, topic_id: topic1.id)
LangTopic.create(language_id: lang14.id, topic_id: topic2.id)
LangTopic.create(language_id: lang14.id, topic_id: topic3.id)
LangTopic.create(language_id: lang14.id, topic_id: topic4.id)
LangTopic.create(language_id: lang14.id, topic_id: topic5.id)
LangTopic.create(language_id: lang14.id, topic_id: topic6.id)
LangTopic.create(language_id: lang14.id, topic_id: topic7.id)
LangTopic.create(language_id: lang14.id, topic_id: topic8.id)
LangTopic.create(language_id: lang14.id, topic_id: topic9.id)
LangTopic.create(language_id: lang14.id, topic_id: topic10.id)
LangTopic.create(language_id: lang14.id, topic_id: topic11.id)
LangTopic.create(language_id: lang14.id, topic_id: topic12.id)
LangTopic.create(language_id: lang14.id, topic_id: topic13.id)
LangTopic.create(language_id: lang14.id, topic_id: topic14.id)
LangTopic.create(language_id: lang14.id, topic_id: topic15.id)
LangTopic.create(language_id: lang14.id, topic_id: topic16.id)
LangTopic.create(language_id: lang14.id, topic_id: topic17.id)
LangTopic.create(language_id: lang14.id, topic_id: topic18.id)
LangTopic.create(language_id: lang14.id, topic_id: topic19.id)

LangTopic.create(language_id: lang15.id, topic_id: topic2.id)
LangTopic.create(language_id: lang15.id, topic_id: topic3.id)
LangTopic.create(language_id: lang15.id, topic_id: topic4.id)
LangTopic.create(language_id: lang15.id, topic_id: topic5.id)
LangTopic.create(language_id: lang15.id, topic_id: topic6.id)
LangTopic.create(language_id: lang15.id, topic_id: topic11.id)
LangTopic.create(language_id: lang15.id, topic_id: topic16.id)
LangTopic.create(language_id: lang15.id, topic_id: topic17.id)
LangTopic.create(language_id: lang15.id, topic_id: topic18.id)
LangTopic.create(language_id: lang15.id, topic_id: topic22.id)
LangTopic.create(language_id: lang15.id, topic_id: topic23.id)
LangTopic.create(language_id: lang15.id, topic_id: topic24.id)
LangTopic.create(language_id: lang15.id, topic_id: topic25.id)
LangTopic.create(language_id: lang15.id, topic_id: topic26.id)
